[package]
name = "datafusion_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
datafusion = "36.0.0"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread"] }
